databases:
  - name: it-dashboard-db
    databaseName: it_dashboard_production
    user: it_dashboard

services:
  - type: web
    name: it-consulting-dashboard
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT -e production"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: it-dashboard-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
